chain precommit scripts and rename the puppet one

diff --git a/.git-init-template/hooks/pre-commit b/.git-init-template/hooks/pre-commit
--- a/.git-init-template/hooks/pre-commit
+++ b/.git-init-template/hooks/pre-commit
@@ -1,47 +1,27 @@
-#!/bin/sh
+#!/bin/bash
 
-syntax_errors=0
-error_msg=$(mktemp /tmp/error_msg.XXXXXX)
+# Runs all executable pre-commit-* hooks and exits after,
+# if any of them was not successful.
+#
+# Based on
+# http://osdir.com/ml/git/2009-01/msg00308.html
 
-if git rev-parse --quiet --verify HEAD > /dev/null
-then
-    against=HEAD
-else
-    # Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
+data=$(cat)
+exitcodes=()
+hookname=`basename $0`
 
-# Get list of new/modified manifest and template files to check (in git index)
-for indexfile in `git diff-index --diff-filter=AM --name-only --cached $against | egrep '\.(pp|erb)'`
-do
-    # Don't check empty files
-    if [ `git cat-file -s :0:$indexfile` -gt 0 ]
-    then
-        case $indexfile in
-            *.pp )
-                # Check puppet manifest syntax
-                #git cat-file blob :0:$indexfile | puppet --color=false --parseonly --ignoreimport > $error_msg ;;
-                # Updated for 2.7.x
-                puppet parser validate $indexfile > $error_msg ;;
-            *.erb )
-                # Check ERB template syntax
-                # -P : ignore lines which start with "%" 
-                git cat-file blob :0:$indexfile | erb -P -x -T - | ruby -c 2> $error_msg > /dev/null ;;
-        esac
-        if [ "$?" -ne 0 ]
-        then
-            echo -n "$indexfile: "
-            cat $error_msg
-            syntax_errors=`expr $syntax_errors + 1`
-        fi
-    fi
+# Run each hook, passing through STDIN and storing the exit code.
+# We don't want to bail at the first failure, as the user might
+# then bypass the hooks without knowing about additional issues.
+
+for hook in $GIT_DIR/hooks/$hookname-*; do
+  test -x "$hook" || continue
+  echo "$data" | "$hook"
+  exitcodes+=($?)
 done
 
-rm -f $error_msg
+# If any exit code isn't 0, bail.
 
-if [ "$syntax_errors" -ne 0 ]
-then
-    echo "Error: $syntax_errors syntax errors found, aborting commit."
-    exit 1
-fi
-
+for i in "${exitcodes[@]}"; do
+  [ "$i" == 0 ] || exit $i
+done
